# Generated by Django 4.0.1 on 2022-01-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkin', '0008_alter_manager_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.FileField(default='', max_length=30, upload_to=''),
            preserve_default=False,
        ),
    ]
