# Generated by Django 4.0.1 on 2022-01-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkin', '0010_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='image',
            field=models.FileField(max_length=255, null=True, upload_to=''),
        ),
    ]
