# Generated by Django 4.0.1 on 2022-02-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkin', '0012_alter_manager_image_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
