# Generated by Django 4.0.1 on 2022-02-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkin', '0013_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='trained',
            field=models.BooleanField(default=False),
        ),
    ]
